name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types:
      - open

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
      - name: Run tests
        run: coverage run test_app.py
      - name: Tests report
        run: coverage report
  
  test_work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show ref_name
        run: echo ${GITHUB_REF_NAME}
      - name: Show sha
        run: |
          echo ${GITHUB_SHA}
          echo ${GITHUB_SHA:30}
          echo ${{ github.event.push }}
  
  build_and_pub:
    if: github.event.pull_request.merged == true || github.event.push
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_USERNAME }}
      NAME: ${{ secrets.DOCKER_FOLDER }}
    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF_NAME} -f Dockerfile .
      - name: Push image to docker
        run: docker push $LOGIN/$NAME:${GITHUB_REF_NAME}
